@startuml
!include ../includes/style.iuml

hide footbox
actor User
participant App

User -> App: Initiate SSE
App --> User: Receive a list of rooms
App -> App: Wait 1s
App --> User: Receive a new list
App -> App: Wait 1s
App --> User: Receive a new list
App -> App: Wait 1s, and so on...


@enduml
