version: "3.7"

services:
  # region Public services
  test-task-app:
    hostname: test_task_best_way-app
    image: test-task-app
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: "pnpm run start:prod"
    depends_on:
      - redis-message-bus
      - mongodb-single-replica
  # endregion

  # region Private services
  redis-message-bus:
    hostname: test_task_best_way-redis
    image: "redis:5.0-alpine"
    ports:
      - "6379:6379"

  mongodb-single-replica:
    image: mongo:5.0.4
    hostname: test_task_best_way-mongodb
    ports:
      - "27037:27037"
    restart: always
    environment:
      - MONGODB_DATABASE="best-way"
    volumes:
      - ./docker/volume/mongodb_local:/data/db
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "27037" ]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'test_task_best_way-mongodb:27037'}]}) }" | mongosh --port 27037 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
  # endregion
